# Generated by Django 5.1.4 on 2024-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visit_count",
            field=models.IntegerField(default=0, verbose_name="조회수"),
        ),
    ]
